name: Zig

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ldc-master
      - uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: nightly
            override: true
      # missing flang support: https://github.com/fortran-lang/setup-fortran/issues/12
      # - uses: fortran-lang/setup-fortran@v1
      #   id: setup-fortran
      #   with:
      #     compiler: flang
      #     version: 19
      - name: (Swift 6) Download & Extract package
        run: |
          if [ "${{ matrix.runs-on }}" = "ubuntu-24.04-arm" ]; then
            curl -LO https://download.swift.org/swift-6.1-release/ubuntu2404-aarch64/swift-6.1-RELEASE/swift-6.1-RELEASE-ubuntu24.04-aarch64.tar.gz
            tar xzf swift-6.1-RELEASE-ubuntu24.04-aarch64.tar.gz
            echo "$PWD/swift-6.1-RELEASE-ubuntu24.04-aarch64/usr/bin" >> $GITHUB_PATH
          else
            curl -LO https://download.swift.org//swift-6.1-release/ubuntu2404/swift-6.1-RELEASE/swift-6.1-RELEASE-ubuntu24.04.tar.gz
            tar xzf swift-6.1-RELEASE-ubuntu24.04.tar.gz
            echo "$PWD/swift-6.1-RELEASE-ubuntu24.04/usr/bin" >> $GITHUB_PATH
          fi      
      - name: get-flang-linux
        run: |
            sudo apt-get update
            sudo apt-get install --no-install-recommends flang
      - name: Build Summary
        run: zig build --build-file $PWD/tests/build.zig --summary all --verbose

  # windows-target:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       runs-on: [windows-latest]
  #   runs-on: ${{ matrix.runs-on }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: mlugg/setup-zig@v1
  #       with:
  #         version: master
  #     - uses: dlang-community/setup-dlang@v2
  #       with:
  #         compiler: ldc-master
  #     - uses: compnerd/gha-setup-swift@main
  #       with:
  #         branch: development
  #         tag: DEVELOPMENT-SNAPSHOT-2024-09-06-a
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #           profile: minimal
  #           toolchain: nightly
  #           override: true
  #     - name: Build Summary
  #       run: zig build --build-file $PWD/tests/build.zig --summary all -freference-trace --verbose

  # macos-target:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       runs-on: [macos-latest]
  #   runs-on: ${{ matrix.runs-on }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: mlugg/setup-zig@v1
  #       with:
  #         version: master
  #     - uses: dlang-community/setup-dlang@v2
  #       with:
  #         compiler: ldc-master
  #     - name: Select Xcode version
  #       run: |
  #         sudo xcode-select -s '/Applications/Xcode_16.0.app/Contents/Developer'
  #         swift --version
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #           profile: minimal
  #           toolchain: nightly
  #           override: true
  #     - name: Build Summary
  #       run: zig build --build-file $PWD/tests/build.zig --summary all -freference-trace --verbose