name: Zig

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-24.04]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ldc-master
      - uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: nightly
            override: true
      # missing flang support: https://github.com/fortran-lang/setup-fortran/issues/12
      # - uses: fortran-lang/setup-fortran@v1
      #   id: setup-fortran
      #   with:
      #     compiler: flang
      #     version: 19
      - name: (Swift 6) Download & Extract packages
        run: |
          curl -LO https://download.swift.org/development/ubuntu2204/swift-DEVELOPMENT-SNAPSHOT-2024-08-21-a/swift-DEVELOPMENT-SNAPSHOT-2024-08-21-a-ubuntu22.04.tar.gz
          tar xzf swift-DEVELOPMENT-SNAPSHOT-2024-08-21-a-ubuntu22.04.tar.gz
          echo "$PWD/swift-DEVELOPMENT-SNAPSHOT-2024-08-21-a-ubuntu22.04/usr/bin" >> $GITHUB_PATH
      - name: get-flang-linux
        run: |
            sudo apt-get update
            sudo apt-get install --no-install-recommends flang
      - name: Build Summary
        run: zig build --summary all --verbose
