name: Zig

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: korandoru/setup-zig@v1
        with:
          zig-version: master
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-master
      - uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: nightly
            override: true
      # - uses: fortran-lang/setup-fortran@v1
      #   id: setup-fortran
      #   with:
      #     compiler: flang
      #     version: 19

      - name: Build Summary
        run: zig build --summary all --verbose
